### ISSUE TITLE
Sort checklist items by deadline, soonest first

### ISSUE THREAD

**Issue by RobRuana** [magfest/guests#102]
The `sorted_checklist` [here](https://github.com/magfest/guests/blob/4959350481d26cbd74192750ae6334b022683675/guests/site_sections/guests.py#L17) is never actually sorted. We need to do something like this:

```python
return {
    'message': message,
    'guest': guest,
    'sorted_checklist': sorted(sorted_checklist, key=lambda x: guest.deadline_from_model(x['name']))
}
```

# Checklist items out of order:
<img width="859" alt="screen shot 2017-09-21 at 11 08 07 am" src="https://user-images.githubusercontent.com/2592431/30703288-4b1fe150-9ebd-11e7-96cc-01ef79f24a07.png">

**Comment by kitsuta** [comment]
Oh, whoops.. I had that working at one point! Good catch! 😅
