### ISSUE TITLE
Add Rock Island merch info collection

### ISSUE THREAD

**Issue by dlenik** [magfest/guests#93]
Add fields from this .pdf to a form for any performers who request Rock Island services for Super. The deadline for performers to indicate interest in RI is September 30, so at latest it could be completed by then.

[MAGLabs - Rock Island Merch Submission.pdf](https://github.com/magfest/bands/files/1228999/MAGLabs.-.Rock.Island.Merch.Submission.pdf)

**Comment by RobRuana** [comment]
Pulled the fields out of the PDF for easier access:

- MERCH TYPE
  - CD
  - APPAREL (for wearables)
    - Cut
    - Size
    - Style
    - Etc...
    - EX: CryingDustPile T-Shirt Slim cut - S is a separate item from CryingDustPile T-Shirt Slim cut - L
  - PIN
  - STICKER
  - POSTER
  - MISC (for miscellaneous)
- MERCH NAME
- Quantity of item
- A thumbnail (square image) of your product
  - Ideally an album cover for CDs/albums, or a picture of your product
  - TO REITERATE - We want a high resolution image for your ALBUM COVER/MERCH and not a camera phone picture of it
  - We'll print them out, so send us a good resolution! ;)
  - It is not necessary to send an image for each separate item if they have the same image, e.g. different sized shirts
  - the picture should be either a JPG, JPEG, PNG, or a PDF file format.
- Price to sell each item for
- Please remember to include the tax and square fee into your pricing as we will not calculate them at the time of our sale
  - Sales Tax: 6%; Square Fees: ( https://squareup.com/pricing )
- You may also send in up to SIX TRACKS preferably at least one from each album) you are selling for us to make available for listening at the table
- Track files should be in mp3, m4a, or wav format
  - mp3 and m4a are preferable as they allow for saving of meta data like the album art
- If you're going to have any boxes, please let us know how big they are; we would like to plan accordingly
